import React from "react";
import { makeStyles } from '@material-ui/core/styles';
import { Link } from "react-router-dom";

import Card from '@material-ui/core/Card';
import CardActions from '@material-ui/core/CardActions';
import CardContent from '@material-ui/core/CardContent';
import Button from '@material-ui/core/Button';
import Typography from '@material-ui/core/Typography';

import netCoreLogo from './Resources/netCore.svg';
import postgresLogo from './Resources/postgresql.svg';
import reactLogo from './Resources/react.svg';
import muiLogo from './Resources/materialUi.svg'

const useStyles = makeStyles((theme) => ({
    redirectButton: {
        marginBottom: '10px',
        marginLeft: '10px',
        width: "10rem",
    },
    mainCard: {
        margin: '0 auto',
        marginTop: '32px',
        display: 'block',
        maxWidth: 850,
        background: '#6a719b',
        "& p": {
            textAlign: 'justify',
            marginBottom: '16px'
        }
    },
    cards: {
        display: 'flex',
    },
    innerCard: {
        background: '#fdfdfd',
        width: '99%',
        margin: '0 5px',
        "& p": {
            marginBottom: '2px',
            color: 'black',
            fontWeight: 550
        },
        '& span': {
            color: '#2d2d2d',
            marginLeft: '6px',
        },
        '& img': {
            width: '90px',
            height: '90px'
        }
    },
    loginData: {
        display: 'flex',
        justifyContent: 'space-between',
        '& div': {
            width: 'fit-content',
            padding: '6px'
        },
    },
    techBox: {
        display: 'flex',
        justifyContent: 'space-around',
        '& div': {
            margin: '0 15px'
        },
        "& p": {
            margin: '0',
            textAlign: 'center'
        }
    }
}));

const StartPage = () => {
    const classes = useStyles();

    return (
        <div>
            <Card className={classes.mainCard}>
                <CardContent>
                    <Typography gutterBottom variant="h5" component="h2">
                        Human Resources Manager
                    </Typography>
                    <Typography variant="body1" color="textSecondary" component="p">
                        A complex prototype application. To store employees data, and assign tasks to them.
                        Application content is depends of a employee permissions.
                        The main roles of employees are: a regular employee, team leader, administrator, and HR manager.
                        An ordinary employees can view their tasks and change their status.
                        Tasks for employees are assigned by the team leader in a dedicated view.
                        An employee who manages human resources can add new employees and change their data. It is also responsible for creating new teams.
                        All data in the application is randomly generated by a built-in generator on the backend side.
                    </Typography>
                    <Typography variant="body1" color="textSecondary" component="p">
                        To get started you need to login(button below).
                        Login data for main roles are listed below. After login, application will generate new tasks for employees.
                        This is mainly intended for presentation purposes. This is to simulate the use of applications under normal working conditions.
                    </Typography>
                    <Typography variant="h5" component="p">
                        Login Data:
                    </Typography>
                    <Card className={classes.innerCard} style={{ marginBottom: '12px' }}>
                        <CardContent className={classes.loginData}>
                            <div>
                                <Typography variant="subtitle1" component="p">
                                    Administrator
                                </Typography>
                                <Typography variant="body1" component="p">
                                    Login:
                                    <Typography variant="body1" component="span">
                                        admin
                                    </Typography>
                                </Typography>
                                <Typography variant="body1" component="p">
                                    Password:
                                    <Typography variant="body1" component="span">
                                        admin123
                                    </Typography>
                                </Typography>
                            </div>
                            <div>
                                <Typography variant="subtitle1" component="p">
                                    Team Leader
                                </Typography>
                                <Typography variant="body1" component="p">
                                    Login:
                                    <Typography variant="body1" component="span">
                                        leader
                                    </Typography>
                                </Typography>
                                <Typography variant="body1" component="p">
                                    Password:
                                    <Typography variant="body1" component="span">
                                        leader123
                                    </Typography>
                                </Typography>
                            </div>
                            <div>
                                <Typography variant="subtitle1" component="p">
                                    HR Manager
                                </Typography>
                                <Typography variant="body1" component="p">
                                    Login:
                                    <Typography variant="body1" component="span">
                                        hrmanager
                                    </Typography>
                                </Typography>
                                <Typography variant="body1" component="p">
                                    Password:
                                    <Typography variant="body1" component="span">
                                        hr123
                                    </Typography>
                                </Typography>
                            </div>
                            <div>
                                <Typography variant="subtitle1" component="p">
                                    Regular User
                                </Typography>
                                <Typography variant="body1" component="p">
                                    Login:
                                    <Typography variant="body1" component="span">
                                        user
                                    </Typography>
                                </Typography>
                                <Typography variant="body1" component="p">
                                    Password:
                                    <Typography variant="body1" component="span">
                                        user123
                                    </Typography>
                                </Typography>
                            </div>
                        </CardContent>
                    </Card>
                    <Typography variant="h5" component="p">
                        Used Technologies:
                    </Typography>
                    <div className={classes.cards}>
                        <Card className={classes.innerCard}>
                            <CardContent>
                                <Typography variant="h6" component="p">
                                    Backend:
                                </Typography>
                                <div className={classes.techBox}>
                                    <div>
                                        <img src={netCoreLogo} alt=".net core"></img>
                                        <Typography variant="subtitle1" component="p">
                                            .Net Core
                                        </Typography>
                                    </div>
                                    <div>
                                        <img src={postgresLogo} alt="postgres"></img>
                                        <Typography variant="subtitle1" component="p">
                                            PostgreSQL
                                        </Typography>
                                    </div>

                                </div>
                            </CardContent>
                        </Card>
                        <Card className={classes.innerCard}>
                            <CardContent>
                                <Typography variant="h6" component="p">
                                    Frontend:
                                </Typography>
                                <div className={classes.techBox}>
                                    <div>
                                        <img src={reactLogo} alt="React"></img>
                                        <Typography variant="subtitle1" component="p">
                                            ReactJS
                                        </Typography>
                                    </div>
                                    <div>
                                        <img src={muiLogo} alt="MaterialUI"></img>
                                        <Typography variant="subtitle1" component="p">
                                            MaterialUI
                                        </Typography>
                                    </div>

                                </div>
                            </CardContent>
                        </Card>
                    </div>
                </CardContent>
                <CardActions>
                    <Link style={{ textDecoration: "none" }} to="/login">
                        <Button
                            className={classes.redirectButton}
                            variant="contained"
                            color="primary"
                        >To Login Page</Button>
                    </Link>
                </CardActions>
            </Card>

        </div>
    );
}
export default StartPage;